input_device_name: "BlackHole 2ch"
output_device_name: "Scarlett"
samplerate: 96000
blocksize: 512
latency: 0

audio_paths:
  - name: "Stereo Speakers"
    in_channels: [0, 1]
    out_channels: [0, 1]
    gain_db: 0
    invert: false
    eq_bands:
      - {type: HighPassFilter,  frequency: 60,    steepness: 24,  q: 0.707}
      - {type: ParametricBand,  frequency: 67,    gain_db: -3,    q: 4}
      - {type: ParametricBand,  frequency: 76,    gain_db: 6,     q: 4}
      - {type: ParametricBand,  frequency: 112,   gain_db: -9,    q: 4}
      - {type: ParametricBand,  frequency: 130,   gain_db: 9,     q: 4}
      - {type: ParametricBand,  frequency: 185,   gain_db: -6,    q: 1}
      - {type: ParametricBand,  frequency: 286,   gain_db: 3,     q: 1}
      - {type: ParametricBand,  frequency: 560,   gain_db: 6,     q: 4}
      - {type: ParametricBand,  frequency: 896,   gain_db: 6,     q: 4}

  - name: "Subwoofer"
    in_channels: [0, 1]
    out_channels: [2]
    mono_mix: true
    gain_db: -3
    invert: true
    eq_bands:
      - {type: HighPassFilter,  frequency: 30,    steepness: 48,  q: 1}
      - {type: LowShelf,        frequency: 43,    gain_db: 9,     q: 0.8}
      - {type: ParametricBand,  frequency: 46,    gain_db: -6,    q: 4}
      - {type: LowPassFilter,   frequency: 60,    steepness: 24,  q: 0.707}